### ISSUE TITLE
no decompose_kernel 

### ISSUE THREAD

**Issue by miaozhang0525** [zi-w/Structural-Kernel-Learning-for-HDBBO#2]
Hi Zi Wang,

I found that there is no 'decompose kernel' when I am running example_batch_addgp.m.
I could run example_addgp.m

And I could not find where is the 'decompose kernel' function.

**Comment by zi-w** [comment]
Hi, thanks for pointing this out. I added the paths for decompose_kernel and others. Please check example_batch_addgp.m again.

**Comment by miaozhang0525** [comment]
YES!!!! I find it works!! THANKS!
